---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: "{% if selection_mode == \"random\" %}\r\nhttps://usetrmnl.com/custom_plugin_example_data.json\r\n{% else %}\r\nhttps://abacus.jasoncameron.dev/hit/trmnl-lego-sets-plugin/sets-{{trmnl.user.id}}\r\n{% endif %}\r\n\r\nhttps://raw.githubusercontent.com/ExcuseMi/trmnl-lego-plugin/refs/heads/main/data/sets.txt"
polling_headers: ''
polling_body: ''
id: 184371
custom_fields:
- keyname: selection_mode
  name: Set Selection Mode
  field_type: select
  description: Choose how sets should be selected each time the plugin runs.
  options:
  - Random
  - Incremental
  - Reverse Incremental
  default: Random
  optional: true
name: Lego Sets
refresh_interval: 15
